#ifndef __SCT_FSM_H__
#define __SCT_FSM_H__

/* Generated by fzmparser version 2.8 --- DO NOT EDIT! */

#include "sct_user.h"

extern void sct_fsm_init (void);


/* Match register reload macro definitions */
#define sct_fsm_reload_match0(value) do {LPC_SCT->MATCHREL[0].U = value;} while(0)

#endif
