
/* Generated by fzmparser version 2.8 --- DO NOT EDIT! */

/* Uses following resources: */
/* 1 events, 2+0 states, 0 inputs, 0 outputs, 1+0 match regs, 0+0 capture regs */

#include "sct_fsm.h"


void sct_fsm_init (void)
{
LPC_SCT->CONFIG = (LPC_SCT->CONFIG & ~0x00060001) | 0x00000001; /* UNIFIED */

/* MATCH/CAPTURE registers */

/* Unified counter - register side L is used and accessed as 32 bit value, reg H is not used */
LPC_SCT->REGMODE_L = 0x00000000;         /* U: 1x MATCH, 0x CAPTURE, 4 unused */

LPC_SCT->MATCH[0].U = delay;             /* match0 */
LPC_SCT->MATCHREL[0].U = delay;

/* OUTPUT registers */
  /* Unused outputs must not be affected by any event */
LPC_SCT->OUT[0].SET = 0;
LPC_SCT->OUT[0].CLR = 0;
LPC_SCT->OUT[1].SET = 0;
LPC_SCT->OUT[1].CLR = 0;
LPC_SCT->OUT[2].SET = 0;
LPC_SCT->OUT[2].CLR = 0;
LPC_SCT->OUT[3].SET = 0;
LPC_SCT->OUT[3].CLR = 0;

/* Conflict resolution register */

/* EVENT registers */
LPC_SCT->EV[0].CTRL = 0x00081000;     /* U: --> state -16 */
LPC_SCT->EV[0].STATE = 0x00010001;
  /* Unused events must not have any effect */
LPC_SCT->EV[1].STATE = 0;
LPC_SCT->EV[2].STATE = 0;
LPC_SCT->EV[3].STATE = 0;
LPC_SCT->EV[4].STATE = 0;
LPC_SCT->EV[5].STATE = 0;

/* STATE registers */
LPC_SCT->STATE_L = 0;

/* state names assignment: */
  /* State U 0: U_ENTRY */
  /* State U16: LED_ON */

/* CORE registers */
LPC_SCT->START_L = 0x00000000;
LPC_SCT->STOP_L =  0x00000000;
LPC_SCT->HALT_L =  0x00000000;
LPC_SCT->LIMIT_L = 0x00000001;
LPC_SCT->EVEN =    0x00000000;

}
